package HibernateCode;

// Generated 2016-6-28 19:34:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userid;
	private String phonenumber;
	private String md5code;
	private String md5password;
	private String token;
	private String nickname;
	private String headportrait;
	private String sex;
	private String signature;
	private String place;
	private Date registtime;

	public User() {
	}

	public User(int userid, String phonenumber, String md5code,
			String md5password, String token, String nickname,
			String headportrait, String sex, Date registtime) {
		this.userid = userid;
		this.phonenumber = phonenumber;
		this.md5code = md5code;
		this.md5password = md5password;
		this.token = token;
		this.nickname = nickname;
		this.headportrait = headportrait;
		this.sex = sex;
		this.registtime = registtime;
	}

	public User(int userid, String phonenumber, String md5code,
			String md5password, String token, String nickname,
			String headportrait, String sex, String signature, String place,
			Date registtime) {
		this.userid = userid;
		this.phonenumber = phonenumber;
		this.md5code = md5code;
		this.md5password = md5password;
		this.token = token;
		this.nickname = nickname;
		this.headportrait = headportrait;
		this.sex = sex;
		this.signature = signature;
		this.place = place;
		this.registtime = registtime;
	}
	
	public void setInfoByInfoname(String infoname, String infovalue){
		if ("nickname".equals(infoname)){
			this.nickname = infovalue;
		}
		else if ("headportrait".equals(infoname)) {
			this.headportrait = infovalue;
		}
		else if ("sex".equals(infoname)) {
			this.sex = infovalue;
		}
		else if ("signature".equals(infoname)) {
			this.signature = infovalue;
		}
		else if ("place".equals(infoname)) {
			this.place = infovalue;
		}
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	public String getMd5code() {
		return this.md5code;
	}

	public void setMd5code(String md5code) {
		this.md5code = md5code;
	}

	public String getMd5password() {
		return this.md5password;
	}

	public void setMd5password(String md5password) {
		this.md5password = md5password;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getHeadportrait() {
		return this.headportrait;
	}

	public void setHeadportrait(String headportrait) {
		this.headportrait = headportrait;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public Date getRegisttime() {
		return this.registtime;
	}

	public void setRegisttime(Date registtime) {
		this.registtime = registtime;
	}

}
